// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartX.Infrastructure.Persistence;

#nullable disable

namespace SmartX.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartXDbContext))]
    partial class SmartXDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartX.Domain.Entities.DeploymentNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("NodeType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("DeploymentNodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_DeploymentNodes_NodeType", "[NodeType] BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("SmartX.Domain.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<Guid>("DeploymentNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("ExpectedMaximum")
                        .HasColumnType("float");

                    b.Property<double?>("ExpectedMinimum")
                        .HasColumnType("float");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("MeasuredProperty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ValueKind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentNodeId");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.ToTable("Sensors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sensors_BooleanRange", "[ValueKind] <> 3 OR ([ExpectedMinimum] IS NULL AND [ExpectedMaximum] IS NULL)");

                            t.HasCheckConstraint("CK_Sensors_Category", "[Category] BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_Sensors_ExpectedRange", "([ExpectedMinimum] IS NULL AND [ExpectedMaximum] IS NULL) OR ([ExpectedMinimum] IS NOT NULL AND [ExpectedMaximum] IS NOT NULL AND [ExpectedMinimum] <= [ExpectedMaximum])");

                            t.HasCheckConstraint("CK_Sensors_ValueKind", "[ValueKind] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("SmartX.Infrastructure.Persistence.Entities.SensorAttachmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("RelativePath")
                        .IsUnique();

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.HasIndex("SensorId", "UploadedAtUtc");

                    b.ToTable("SensorAttachments", null, t =>
                        {
                            t.HasCheckConstraint("CK_SensorAttachments_Category", "[Category] BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_SensorAttachments_SizeBytes", "[SizeBytes] > 0");
                        });
                });

            modelBuilder.Entity("SmartX.Infrastructure.Persistence.Entities.TelemetryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("bit");

                    b.Property<float?>("FloatValue")
                        .HasColumnType("real");

                    b.Property<int?>("IntegerValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ValueKind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SensorId", "RecordedAtUtc");

                    b.ToTable("TelemetryRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_TelemetryRecords_TypedValue", "([ValueKind] = 1 AND [FloatValue] IS NOT NULL AND [IntegerValue] IS NULL AND [BooleanValue] IS NULL) OR ([ValueKind] = 2 AND [FloatValue] IS NULL AND [IntegerValue] IS NOT NULL AND [BooleanValue] IS NULL) OR ([ValueKind] = 3 AND [FloatValue] IS NULL AND [IntegerValue] IS NULL AND [BooleanValue] IS NOT NULL)");

                            t.HasCheckConstraint("CK_TelemetryRecords_Validation", "([IsValid] = 1 AND [ValidationMessage] IS NULL) OR ([IsValid] = 0 AND [ValidationMessage] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SmartX.Domain.Entities.DeploymentNode", b =>
                {
                    b.HasOne("SmartX.Domain.Entities.DeploymentNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SmartX.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("SmartX.Domain.Entities.DeploymentNode", "DeploymentNode")
                        .WithMany()
                        .HasForeignKey("DeploymentNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeploymentNode");
                });

            modelBuilder.Entity("SmartX.Infrastructure.Persistence.Entities.SensorAttachmentRecord", b =>
                {
                    b.HasOne("SmartX.Domain.Entities.Sensor", null)
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartX.Infrastructure.Persistence.Entities.TelemetryRecord", b =>
                {
                    b.HasOne("SmartX.Domain.Entities.Sensor", null)
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartX.Domain.Entities.DeploymentNode", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
